rules: accept "deps: V8" as the subsystem for revert commits
The commit, https://github.com/nodejs/node/pull/45119/commits/cbb404503c9df13aaeb3dd8b345cb3f34c8c07e4,
was being flagged as invalid by core-validate-commit because of this
error:
```txt
Error: not ok 6 title-format: First word after subsystem(s) in title should be lowercase. (Revert "deps: V8: forward declaration of `Rtl*FunctionTable`")
```
This is incorrect because "deps: V8" is a valid subsystem. This change
makes sure that revert commits with such a subsystem is accepted.

Signed-off-by: Darshan Sen <raisinten@gmail.com>